sudo: required
language: ruby
rvm:
 - 2.5
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database dad_joke_test;' -U postgres
  - wget http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable
script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rails assets:precompile
  - bundle exec rails test:system test